# Generated by Django 2.2.7 on 2020-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessApp', '0002_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='isCreatedManual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='isUpdatedManual',
            field=models.BooleanField(default=False),
        ),
    ]
